<?php
	echo "------------------------------------------array_merge-------------------------------------------------" . "</br>";
	echo "------------------------------------------------------------------------------------------------------" . "</br>";
// khi muốn kết hợp mảng lại với nhau chúng ta dùng array_merge($var);
	$arr1 = array("anh ", "yeu ", "em");
	$arr2 = array(1,2,3,5);
	$arrayM = array_merge($arr1, $arr2);
	echo "array_merge: " . "</br>";
	echo "<pre>";
	print_r($arrayM );
	echo "</pre>";
 	echo "------------------------------------------array_rand--------------------------------------------------" . "</br>";
	echo "------------------------------------------------------------------------------------------------------" . "</br>";
//khi muốn các phần tử xuất hiện random ta dùng array_rand($var, number);
	$course = array("abc","aaa","eee","rrr","tttt");
	echo "Raw: " . "</br>";
	echo "<pre>";
	print_r($course );
	echo "</pre>";
	$arrayR = array_rand($course, 2);
	echo "array_rand: " . "</br>";
	echo "<pre>";
	print_r($arrayR );
	echo "</pre>";
	echo "------------------------------------------array_search--------------------------------------------------" . "</br>";
	echo "--------------------------------------------------------------------------------------------------------" . "</br>";
	//khi muốn tìm kiến phần tử $key trong array ta dùng aray_search();
	$course1 = array("abc","aaa","eee","rrr","tttt");
	echo "Raw: " . "</br>";
	echo "<pre>";
	print_r($course1 );
	echo "</pre>";
	$arrayS = array_search("rrr", $course1);
	echo "array_rand: " . "</br>";
	echo "<pre>";
	print_r($arrayS );
	echo "</pre>";
	echo "------------------------------------------array_key_exists--------------------------------------------------" . "</br>";
	echo "------------------------------------------------------------------------------------------------------------" . "</br>";
//Muốn kiểm tra key trong array có tồn tại hay không ta dùng array_key_exists();
	$course_key = array("abc","aaa","eee","rrr","tttt");
	echo "Raw: " . "</br>";
	echo "<pre>";
	print_r($course_key );
	echo "</pre>";
	echo "array_key_exists: ";
	if(array_key_exists(3, $course_key)){
		echo "Exists";
	}else{
		echo "Not found....";
	}
	echo "</br>";
	echo "------------------------------------------in_array--------------------------------------------------" . "</br>";
	echo "----------------------------------------------------------------------------------------------------" . "</br>";
//Muốn kiểm tra value trong array có tồn tại hay không ta dùng in_array();
	$course_value = array("abc","aaa","eee","rrr","tttt");
	echo "Raw: " . "</br>";
	echo "<pre>";
	print_r($course_value );
	echo "</pre>";
	echo "in_array: ";
	if(in_array("tttt2", $course_key)){
		echo "Exists";
	}else{
		echo "Not found....";
	}
	echo "</br>";
//Khi chúng ta muốn các phần tử key trong array thành chử in hoa ta dùng array_change_key_case();
	echo "------------------------------------------array_change_key_case--------------------------------------------------" . "</br>";
	echo "-----------------------------------------------------------------------------------------------------------------" . "</br>";
	$courseC = array("abc"=>"abc","aa"=>"aaa","1"=>"eee","zcz"=>"rrr","tttt");
	echo "Raw: " . "</br>";
	echo "<pre>";
	print_r($courseC );
	echo "</pre>";
	$arr_CKC = array_change_key_case($courseC, CASE_UPPER);
	echo "Raw: " . "</br>";
	echo "<pre>";
	print_r($arr_CKC );
	echo "</pre>";
	echo "------------------------------------------implode--------------------------------------------------" . "</br>";
	echo "---------------------------------------------------------------------------------------------------" . "</br>";
// khi muốn chuyển từ array thành string ta dùng implode();
	$arraytoString = array("Nguyen", "van", "A");
	echo "Raw: " . "</br>";
	echo "<pre>";
	print_r($arraytoString);
	echo "</pre>";
	echo "Array to string:      ";
	$str = implode("---", $arraytoString);
	echo $str . "</br>";
	echo "------------------------------------------explode--------------------------------------------------" . "</br>";
	echo "---------------------------------------------------------------------------------------------------" . "</br>";
// khi muốn chuyển từ String thành array ta dùng explode();
	$stringtoArray = "Tran Duc Huy";
	echo "Raw: " . "</br>";
	echo  $stringtoArray ."</br>";
	echo "String to array:      ";
	$arrE = explode(" ", $stringtoArray);
	echo "<pre>";
	print_r($arrE);
	echo "</pre>";
?>